'use client';

import React, { useState, useCallback, useEffect, useRef } from 'react';
import { X, Clock, AlertTriangle, FileText, Copy, CheckCircle2, Gavel, Timer } from 'lucide-react';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type SubmissionDeadline = '72h' | '7d';

interface ActiveSubmission {
  id: string;
  payerName: string;
  cptCode: string;
  procedureName: string;
  submissionType: SubmissionDeadline;
  submittedAt: Date;
  deadlineAt: Date;
  status: 'pending' | 'overdue' | 'resolved';
}

interface SubmissionProps {
  id: string;
  payerName: string;
  cptCode: string;
  procedureName: string;
  submissionType: SubmissionDeadline;
}

// ---------------------------------------------------------------------------
// Sample submissions
// ---------------------------------------------------------------------------

const SAMPLE_SUBMISSIONS: SubmissionProps[] = [
  {
    id: 'sub-1',
    payerName: 'BCBS Texas',
    cptCode: '72148',
    procedureName: 'Lumbar Spine MRI w/o Contrast',
    submissionType: '72h',
  },
  {
    id: 'sub-2',
    payerName: 'Aetna',
    cptCode: '99214',
    procedureName: 'Established Patient Visit Level 4',
    submissionType: '7d',
  },
  {
    id: 'sub-3',
    payerName: 'UnitedHealthcare',
    cptCode: '72149',
    procedureName: 'Lumbar Spine MRI w/ & w/o Contrast',
    submissionType: '72h',
  },
];

// ---------------------------------------------------------------------------
// Default notice template
// ---------------------------------------------------------------------------

function generateDefaultNotice(submission: ActiveSubmission): string {
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const deadlineDate = submission.deadlineAt.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const hoursOverdue = Math.floor(
    (Date.now() - submission.deadlineAt.getTime()) / (1000 * 60 * 60)
  );

  return `FORMAL REGULATORY NOTICE OF DEFAULT & NON-COMPLIANCE
Pursuant to CMS-0057-F Final Rule (42 CFR Parts 422, 438, 456, 457, 476, 482)

Date: ${date}
To: ${submission.payerName} — Medical Director & Compliance Officer
Re: Statutory Deadline Violation — Prior Authorization #MED-${submission.id.toUpperCase()}

NOTICE OF DEFAULT:

This letter constitutes formal notice that ${submission.payerName} has failed to comply with the mandatory prior authorization response deadlines established under CMS-0057-F.

CASE DETAILS:
• Procedure: ${submission.procedureName} (CPT ${submission.cptCode})
• Submission Date: ${submission.submittedAt.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
• Statutory Deadline: ${deadlineDate} (${submission.submissionType === '72h' ? '72 hours — Urgent' : '7 calendar days — Standard'} per CMS-0057-F)
• Current Status: ${hoursOverdue} HOURS PAST DEADLINE — DEFAULT

REGULATORY VIOLATION:

1. CMS-0057-F § 422.138(f) — Failure to provide timely determination
2. 42 CFR § 422.568 — Failure to meet mandatory PA response timeframes
3. State Prompt-Pay Statute (applicable state law) — Constructive approval may apply

REMEDIES DEMANDED:

(a) IMMEDIATE approval of the above-referenced prior authorization request as constructively granted per statutory default;
(b) Written confirmation of approval within 24 hours;
(c) Explanation of cause for delay and corrective action plan to prevent recurrence.

Failure to comply within 5 business days will result in immediate escalation to:
• Centers for Medicare & Medicaid Services (CMS)
• State Insurance Commissioner
• Office of Inspector General (OIG)
• ERISA Plan Administrator (if applicable)

This notice is auto-generated by MedHero PriorAuth AI CMS-0057-F Enforcer and constitutes formal regulatory correspondence.

— MedHero PriorAuth AI Compliance System`;
}

// ---------------------------------------------------------------------------
// Countdown timer component
// ---------------------------------------------------------------------------

function CountdownTimer({ deadline, isOverdue }: { deadline: Date; isOverdue: boolean }) {
  const [timeLeft, setTimeLeft] = useState('');

  useEffect(() => {
    const update = () => {
      const now = Date.now();
      const diff = deadline.getTime() - now;

      if (diff <= 0) {
        const overdueMs = Math.abs(diff);
        const hours = Math.floor(overdueMs / (1000 * 60 * 60));
        const mins = Math.floor((overdueMs % (1000 * 60 * 60)) / (1000 * 60));
        const secs = Math.floor((overdueMs % (1000 * 60)) / 1000);
        setTimeLeft(`+${hours}h ${mins}m ${secs}s OVERDUE`);
      } else {
        const hours = Math.floor(diff / (1000 * 60 * 60));
        const mins = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
        const secs = Math.floor((diff % (1000 * 60)) / 1000);
        if (hours > 0) {
          setTimeLeft(`${hours}h ${mins}m ${secs}s remaining`);
        } else if (mins > 0) {
          setTimeLeft(`${mins}m ${secs}s remaining`);
        } else {
          setTimeLeft(`${secs}s remaining`);
        }
      }
    };

    update();
    const interval = setInterval(update, 1000);
    return () => clearInterval(interval);
  }, [deadline]);

  return (
    <span
      className={`text-xs font-mono font-bold tabular-nums ${
        isOverdue ? 'text-status-red animate-pulse' : 'text-text-primary'
      }`}
    >
      {timeLeft}
    </span>
  );
}

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

interface CMSEnforcerProps {
  isOpen: boolean;
  onClose: () => void;
  payerName?: string | null;
  cptCode?: string | null;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export default function CMSEnforcer({ isOpen, onClose, payerName, cptCode }: CMSEnforcerProps) {
  const [submissions, setSubmissions] = useState<ActiveSubmission[]>([]);
  const [showNoticeModal, setShowNoticeModal] = useState(false);
  const [selectedSubmission, setSelectedSubmission] = useState<ActiveSubmission | null>(null);
  const [copiedNotice, setCopiedNotice] = useState(false);
  const [isInitialized, setIsInitialized] = useState(false);

  // Initialize submissions on first open
  useEffect(() => {
    if (isOpen && !isInitialized) {
      const now = Date.now();
      const subs: ActiveSubmission[] = SAMPLE_SUBMISSIONS.map((s) => {
        const hoursAgo = s.submissionType === '72h' ? 76 : 168;
        // Make some overdue for demo
        const adjustedHours = s.id === 'sub-1' ? 80 : s.id === 'sub-3' ? 50 : 120;
        const submittedAt = new Date(now - adjustedHours * 60 * 60 * 1000);
        const deadlineHours = s.submissionType === '72h' ? 72 : 168;
        const deadlineAt = new Date(submittedAt.getTime() + deadlineHours * 60 * 60 * 1000);
        return {
          ...s,
          submittedAt,
          deadlineAt,
          status: deadlineAt.getTime() < now ? 'overdue' : 'pending',
        };
      });
      setSubmissions(subs);
      setIsInitialized(true);
    }
  }, [isOpen, isInitialized]);

  const handleGenerateNotice = useCallback((submission: ActiveSubmission) => {
    setSelectedSubmission(submission);
    setShowNoticeModal(true);
  }, []);

  const handleCopyNotice = useCallback(() => {
    if (!selectedSubmission) return;
    const notice = generateDefaultNotice(selectedSubmission);
    navigator.clipboard.writeText(notice).then(() => {
      setCopiedNotice(true);
      setTimeout(() => setCopiedNotice(false), 2000);
    });
  }, [selectedSubmission]);

  if (!isOpen) return null;

  const activeCount = submissions.filter((s) => s.status !== 'resolved').length;
  const overdueCount = submissions.filter((s) => s.status === 'overdue').length;

  return (
    <>
      <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
        <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-hidden flex flex-col">
          {/* Header */}
          <div className="flex items-center justify-between px-6 py-4 border-b border-border-light bg-gradient-to-r from-status-red/5 to-accent-gold/5">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-status-red/10">
                <Gavel size={20} className="text-status-red" />
              </div>
              <div>
                <h2 className="text-lg font-semibold text-heading-navy">⚖️ CMS-0057-F Enforcer</h2>
                <p className="text-xs text-text-secondary">Statutory deadline monitoring &amp; automatic non-compliance notices</p>
              </div>
            </div>
            <button onClick={onClose} className="p-2 rounded-lg hover:bg-black/5 transition-colors">
              <X size={18} className="text-text-secondary" />
            </button>
          </div>

          {/* Body */}
          <div className="flex-1 overflow-y-auto p-6 space-y-5">
            {/* Summary Banner */}
            <div className="grid grid-cols-3 gap-3">
              <div className="rounded-xl border border-border-light bg-white p-3 text-center">
                <p className="text-2xl font-extrabold text-heading-navy">{submissions.length}</p>
                <p className="text-[10px] text-text-secondary mt-1">Total Tracked</p>
              </div>
              <div className="rounded-xl border border-accent-gold/30 bg-accent-gold/5 p-3 text-center">
                <p className="text-2xl font-extrabold text-accent-gold">{activeCount}</p>
                <p className="text-[10px] text-text-secondary mt-1">Active</p>
              </div>
              <div className="rounded-xl border border-status-red/30 bg-status-red/5 p-3 text-center">
                <p className="text-2xl font-extrabold text-status-red">{overdueCount}</p>
                <p className="text-[10px] text-text-secondary mt-1">Overdue ⚠️</p>
              </div>
            </div>

            {/* CMS-0057-F Reference */}
            <div className="rounded-xl border border-accent-blue/20 bg-accent-blue/3 p-4">
              <div className="flex items-start gap-3">
                <div className="p-2 rounded-full bg-accent-blue/10 flex-shrink-0">
                  <Clock size={16} className="text-accent-blue" />
                </div>
                <div>
                  <h4 className="text-xs font-bold text-heading-navy">CMS-0057-F Mandatory Deadlines</h4>
                  <div className="mt-2 space-y-1.5">
                    <div className="flex items-center gap-2">
                      <span className="px-2 py-0.5 rounded-full bg-status-red/10 text-status-red text-[9px] font-bold">
                        URGENT
                      </span>
                      <span className="text-[10px] text-text-primary">
                        <strong>72 hours</strong> — Urgent/emergency prior authorization requests
                      </span>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="px-2 py-0.5 rounded-full bg-accent-gold/10 text-heading-navy text-[9px] font-bold">
                        STANDARD
                      </span>
                      <span className="text-[10px] text-text-primary">
                        <strong>7 calendar days</strong> — Standard prior authorization requests
                      </span>
                    </div>
                  </div>
                  <p className="text-[10px] text-text-secondary mt-2 leading-relaxed">
                    If the payer fails to respond within the statutory deadline, the authorization may be deemed constructively
                    approved. CMS-0057-F enforces mandatory compliance with these timeframes.
                  </p>
                </div>
              </div>
            </div>

            {/* Active Submissions */}
            <div>
              <h4 className="text-xs font-bold text-text-primary mb-3 flex items-center gap-2">
                <Timer size={14} className="text-accent-blue" />
                Active Submission Clocks
              </h4>
              <div className="space-y-3">
                {submissions.map((submission) => {
                  const isOverdue = submission.status === 'overdue';
                  const now = Date.now();
                  const hoursRemaining = Math.floor(
                    (submission.deadlineAt.getTime() - now) / (1000 * 60 * 60)
                  );
                  const totalHours = submission.submissionType === '72h' ? 72 : 168;
                  const elapsedPercent = Math.min(
                    100,
                    Math.max(0, ((totalHours - hoursRemaining) / totalHours) * 100)
                  );

                  return (
                    <div
                      key={submission.id}
                      className={`rounded-xl border-2 p-4 transition-all duration-300 ${
                        isOverdue
                          ? 'border-status-red/40 bg-status-red/3 animate-pulse'
                          : hoursRemaining <= 4
                            ? 'border-status-orange/30 bg-status-orange/3'
                            : 'border-border-light bg-white'
                      }`}
                    >
                      <div className="flex items-start justify-between mb-3">
                        <div>
                          <div className="flex items-center gap-2 flex-wrap">
                            <span className="text-xs font-bold text-text-primary">
                              {submission.payerName}
                            </span>
                            <span className="text-[9px] font-semibold px-2 py-0.5 rounded-full bg-bg-navy/10 text-bg-navy">
                              CPT {submission.cptCode}
                            </span>
                            <span
                              className={`text-[9px] font-bold px-2 py-0.5 rounded-full ${
                                submission.submissionType === '72h'
                                  ? 'bg-status-red/10 text-status-red'
                                  : 'bg-accent-gold/10 text-heading-navy'
                              }`}
                            >
                              {submission.submissionType === '72h' ? '72-HR URGENT' : '7-DAY STANDARD'}
                            </span>
                          </div>
                          <p className="text-[10px] text-text-secondary mt-1">{submission.procedureName}</p>
                        </div>
                      </div>

                      {/* Progress bar */}
                      <div className="mb-2">
                        <div className="flex items-center justify-between mb-1">
                          <span className="text-[9px] text-text-secondary">Deadline progress</span>
                          <CountdownTimer deadline={submission.deadlineAt} isOverdue={isOverdue} />
                        </div>
                        <div className="h-2 rounded-full bg-bg-secondary overflow-hidden">
                          <div
                            className={`h-full rounded-full transition-all duration-1000 ${
                              isOverdue ? 'bg-status-red' : elapsedPercent > 85 ? 'bg-status-orange' : 'bg-accent-blue'
                            }`}
                            style={{ width: `${Math.min(100, elapsedPercent)}%` }}
                          />
                        </div>
                        <div className="flex justify-between mt-1">
                          <span className="text-[9px] text-text-secondary/60">
                            Submitted: {submission.submittedAt.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
                          </span>
                          <span className="text-[9px] text-text-secondary/60">
                            Deadline: {submission.deadlineAt.toLocaleDateString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}
                          </span>
                        </div>
                      </div>

                      {/* Action button for overdue */}
                      {isOverdue && (
                        <button
                          onClick={() => handleGenerateNotice(submission)}
                          className="w-full mt-2 flex items-center justify-center gap-2 px-3 py-2 rounded-lg
                                     bg-status-red text-white text-[10px] font-bold
                                     hover:brightness-110 transition-all shadow-sm"
                        >
                          <Gavel size={12} />
                          🚨 Generate Formal Notice of Default &amp; Non-Compliance
                        </button>
                      )}

                      {!isOverdue && hoursRemaining <= 4 && (
                        <div className="flex items-center gap-2 mt-2 px-3 py-2 rounded-lg bg-status-orange/10 border border-status-orange/20">
                          <AlertTriangle size={12} className="text-status-orange" />
                          <span className="text-[10px] font-semibold text-status-orange">
                            ⚠️ Deadline approaching — prepare default notice
                          </span>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Guidelines Reference */}
            <div className="rounded-xl border border-border-light bg-bg-secondary p-4">
              <h4 className="text-xs font-bold text-text-primary mb-2">Applicable Regulations</h4>
              <ul className="space-y-1 text-[10px] text-text-secondary">
                <li>• CMS-0057-F Final Rule (Federal Register, Feb 8, 2024)</li>
                <li>• 42 CFR § 422.138(f) — Timely determination requirements</li>
                <li>• 42 CFR § 422.568 — Standard timeframes for organization determinations</li>
                <li>• State Prompt-Pay Statutes (varies by state — constructive approval may apply)</li>
                <li>• ERISA § 503 — Claims procedure requirements</li>
              </ul>
            </div>
          </div>

          {/* Footer */}
          <div className="px-6 py-3 border-t border-border-light bg-bg-secondary flex justify-end">
            <button
              onClick={onClose}
              className="px-4 py-2 rounded-lg text-xs font-medium text-text-secondary border border-border-light hover:bg-white transition-colors"
            >
              Close
            </button>
          </div>
        </div>
      </div>

      {/* Notice Modal */}
      {showNoticeModal && selectedSubmission && (
        <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[85vh] overflow-hidden flex flex-col">
            {/* Modal Header */}
            <div className="flex items-center justify-between px-6 py-4 border-b border-status-red/20 bg-status-red/5">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-status-red/10">
                  <Gavel size={20} className="text-status-red" />
                </div>
                <div>
                  <h2 className="text-lg font-semibold text-heading-navy">
                    🚨 Formal Regulatory Notice of Default &amp; Non-Compliance
                  </h2>
                  <p className="text-xs text-text-secondary">
                    CMS-0057-F deadline exceeded — {selectedSubmission.payerName}
                  </p>
                </div>
              </div>
              <button
                onClick={() => setShowNoticeModal(false)}
                className="p-2 rounded-lg hover:bg-black/5 transition-colors"
              >
                <X size={18} className="text-text-secondary" />
              </button>
            </div>

            {/* Modal Body */}
            <div className="flex-1 overflow-y-auto p-6">
              <div className="rounded-xl border border-border-light bg-bg-secondary p-5 max-h-96 overflow-y-auto">
                <pre className="text-[10px] text-text-primary font-mono whitespace-pre-wrap leading-relaxed">
                  {generateDefaultNotice(selectedSubmission)}
                </pre>
              </div>
            </div>

            {/* Modal Footer */}
            <div className="px-6 py-3 border-t border-border-light bg-bg-secondary flex justify-end gap-3">
              <button
                onClick={() => setShowNoticeModal(false)}
                className="px-4 py-2 rounded-lg text-xs font-medium text-text-secondary border border-border-light hover:bg-white transition-colors"
              >
                Close
              </button>
              <button
                onClick={handleCopyNotice}
                className="flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-bold text-white bg-status-red hover:brightness-110 transition-all shadow-sm"
              >
                {copiedNotice ? (
                  <>
                    <CheckCircle2 size={12} />
                    Copied!
                  </>
                ) : (
                  <>
                    <Copy size={12} />
                    Copy to Clipboard
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
